# Generated by Django 4.1.7 on 2023-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название действия')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
        ),
    ]
